affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: application-group
          operator: In
          values:
          - {{ cookiecutter.global_platform_shared_resource_identifier }}
