#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#        see https://cert-manager.io/docs/
#------------------------------------------------------------------------------
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: no-reply@{{ cookiecutter.global_root_domain }}
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: {{ cookiecutter.global_aws_region }}
            hostedZoneID: {{ cookiecutter.global_aws_route53_hosted_zone_id }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: wild-openedx-{{ cookiecutter.environment_name }}-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: {{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
  dnsNames:
    - "*.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}"
