apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-recommender-metrics-server
  namespace: vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       metrics-server
  updatePolicy:
    updateMode: "Auto"
