#------------------------------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com/
#
# date: Mar-2023
#
# usage: gather environment variables and add to a tags dict
#------------------------------------------------------------------------------

data "template_file" "cookiecutter_version" {
  template = file("${path.module}/../../../VERSION")
}

# get the commit date of the most recent commit from the repo containing this code
# HINT: this will be a repo generated by the Cookiecutter (ie. openedx_devops)
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_github_commit_date" {
  provisioner "local-exec" {
    command = <<-EOT
    cookiecutter_github_commit_date=$(date -r $(git log -1 --format=%ct) +%Y%m%dT%H%M%S)
    echo $cookiecutter_github_commit_date > ${path.module}/output/cookiecutter_github_commit_date.state
    EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_github_commit_date" {
  template = file("${path.module}/output/cookiecutter_github_commit_date.state")
  depends_on = [
    null_resource.cookiecutter_github_commit_date
  ]
}

# get the current version of Terraform running on the machine that is executing
# this module.
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_terraform_version" {
  provisioner "local-exec" {
    command = <<-EOT
    cookiecutter_terraform_version=$(terraform --version | head -n 1 | sed 's/Terraform //')
    echo $cookiecutter_terraform_version > ${path.module}/output/cookiecutter_terraform_version.state
    EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_terraform_version" {
  template = file("${path.module}/output/cookiecutter_terraform_version.state")
  depends_on = [
    null_resource.cookiecutter_terraform_version
  ]
}

# get the system date from the machine running this module
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_timestamp" {
  provisioner "local-exec" {
    command = <<-EOT
    cookiecutter_timestamp=$(date +%Y%m%dT%H%M%S)
    echo $cookiecutter_timestamp > ${path.module}/output/cookiecutter_timestamp.state
    EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_timestamp" {
  template = file("${path.module}/output/cookiecutter_timestamp.state")
  depends_on = [
    null_resource.cookiecutter_timestamp
  ]
}

# get the operating system of the machine running this module
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_os" {
  provisioner "local-exec" {
    command = <<-EOT
      echo $OSTYPE > ${path.module}/output/cookiecutter_os.state
      EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_os" {
  template = file("${path.module}/output/cookiecutter_os.state")
  depends_on = [
    null_resource.cookiecutter_os
  ]
}

# get the url to the remote Github repository from which this code was cloned.
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_github_repository" {
  provisioner "local-exec" {
    command = <<-EOT
    GIT_PARENT_DIRECTORY=$(git rev-parse --show-toplevel)
    cookiecutter_github_repository=$(git -C $GIT_PARENT_DIRECTORY config --get remote.origin.url)
    echo $cookiecutter_github_repository > ${path.module}/output/cookiecutter_github_repository.state
    EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_github_repository" {
  template = file("${path.module}/output/cookiecutter_github_repository.state")
  depends_on = [
    null_resource.cookiecutter_github_repository
  ]
}

# get the branch of the most recent commit
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_github_branch" {
  provisioner "local-exec" {
    command = <<-EOT
    GIT_PARENT_DIRECTORY=$(git rev-parse --show-toplevel)
    cookiecutter_github_branch=$(git -C $GIT_PARENT_DIRECTORY branch | sed 's/* //')
    echo $cookiecutter_github_branch > ${path.module}/output/cookiecutter_github_branch.state
    EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_github_branch" {
  template = file("${path.module}/output/cookiecutter_github_branch.state")
  depends_on = [
    null_resource.cookiecutter_github_branch
  ]
}

# get the sha of the most recent commit
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_github_commit" {
  provisioner "local-exec" {
    command = <<-EOT
    GIT_PARENT_DIRECTORY=$(git rev-parse --show-toplevel)
    cookiecutter_github_commit=$(git -C $GIT_PARENT_DIRECTORY rev-parse HEAD)
    echo $cookiecutter_github_commit > ${path.module}/output/cookiecutter_github_commit.state
    EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_github_commit" {
  template = file("${path.module}/output/cookiecutter_github_commit.state")
  depends_on = [
    null_resource.cookiecutter_github_commit
  ]
}

# get the AWS IAM user of the key pair that AWS CLI is currently using.
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_global_iam_arn" {
  provisioner "local-exec" {
    command = <<-EOT
      cookiecutter_global_iam_arn=$(aws sts get-caller-identity | jq -r '.["Arn"] as $v | "\($v)"')
      echo $cookiecutter_global_iam_arn > ${path.module}/output/cookiecutter_global_iam_arn.state
    EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_global_iam_arn" {
  template = file("${path.module}/output/cookiecutter_global_iam_arn.state")
  depends_on = [
    null_resource.cookiecutter_global_iam_arn
  ]
}

# get the current version of kubectl that is running on the machine executing
# this module.
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_kubectl_version" {
  provisioner "local-exec" {
    command = <<-EOT
      cookiecutter_kubectl_version=$(kubectl version --output=json | jq -r '.["clientVersion"].gitVersion as $v | "\($v)"')
      echo $cookiecutter_kubectl_version > ${path.module}/output/cookiecutter_kubectl_version.state
      EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_kubectl_version" {
  template = file("${path.module}/output/cookiecutter_kubectl_version.state")
  depends_on = [
    null_resource.cookiecutter_kubectl_version
  ]
}

# get the current version of AWS CLI running on the machine that is executing
# this module.
#------------------------------------------------------------------------------
resource "null_resource" "cookiecutter_awscli_version" {
  provisioner "local-exec" {
    command = <<-EOT
      cookiecutter_awscli_version=$(aws --version | awk '{print $1}' | sed 's/aws-cli//')
      cookiecutter_awscli_version=$(echo $cookiecutter_awscli_version | sed 's@/@@')
      echo $cookiecutter_awscli_version > ${path.module}/output/cookiecutter_awscli_version.state
      EOT
  }
  triggers = {
    timestamp = "${timestamp()}"
  }
}
data "template_file" "cookiecutter_awscli_version" {
  template = file("${path.module}/output/cookiecutter_awscli_version.state")
  depends_on = [
    null_resource.cookiecutter_awscli_version
  ]
}
