LMS_HOSTNAME={{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
CMS_HOSTNAME=studio.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
DOCKER_IMAGE_OPENEDX={{ cookiecutter.global_account_id }}.dkr.ecr.{{ cookiecutter.global_aws_region }}.amazonaws.com/openedx:latest
DOCKER_IMAGE_MFE={{ cookiecutter.global_account_id }}.dkr.ecr.{{ cookiecutter.global_aws_region }}.amazonaws.com/mfe:latest
DOCKER_IMAGE_CREDENTIALS={{ cookiecutter.global_account_id }}.dkr.ecr.{{ cookiecutter.global_aws_region }}.amazonaws.com/credentials:latest
DOCKER_IMAGE_BACKUP={{ cookiecutter.global_account_id }}.dkr.ecr.{{ cookiecutter.global_aws_region }}.amazonaws.com/hastexo_backup:latest
