---
CORS_ORIGIN_ALLOW_ALL: true
CORS_ORIGIN_WHITELIST:
- https://{{ cookiecutter.global_root_domain }}
- https://{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
- https://{{ cookiecutter.environment_studio_subdomain }}.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
- https://apps.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
CROSS_DOMAIN_CSRF_COOKIE_DOMAIN: "{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}"
CROSS_DOMAIN_CSRF_COOKIE_NAME: native-csrf-cookie
CSRF_COOKIE_SECURE: true
CSRF_TRUSTED_ORIGINS: []
DCS_SESSION_COOKIE_SAMESITE: lax
DCS_SESSION_COOKIE_SAMESITE_FORCE_ALL: true
ACTIVATION_EMAIL_SUPPORT_LINK: https://{{ cookiecutter.global_root_domain }}/support/
AWS_SES_REGION_ENDPOINT: email.{{ cookiecutter.global_aws_region }}.amazonaws.com
AWS_SES_REGION_NAME: "{{ cookiecutter.global_aws_region }}"
CREDIT_HELP_LINK_URL: https://{{ cookiecutter.global_root_domain }}/support/
DEFAULT_MOBILE_AVAILABLE: false
DEFAULT_EMAIL_LOGO_URL: https://cdn.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
ENTERPRISE_SUPPORT_URL: https://{{ cookiecutter.global_root_domain }}/support/
ENTERPRISE_TAGLINE: "{{ cookiecutter.global_platform_name }}"
FACEBOOK_API_VERSION: v12.0
FEATURES:
  ENABLE_CHANGE_USER_PASSWORD_ADMIN: true
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain  }}"
  ENABLE_COURSEWARE_INDEX: true
  ENABLE_CSMH_EXTENDED: false
  ENABLE_LEARNER_RECORDS: true
  ENABLE_LIBRARY_INDEX: true
  MILESTONES_APP: true
  ENABLE_PREREQUISITE_COURSES: true
  ENABLE_DASHBOARD_SEARCH: false
  AUTH_USE_OPENID_PROVIDER: false
  AUTOMATIC_AUTH_FOR_TESTING: false
  CUSTOM_COURSES_EDX: false
  ENABLE_BULK_ENROLLMENT_VIEW: true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_CORS_HEADERS: true
  ENABLE_COUNTRY_ACCESS: false
  ENABLE_CREDIT_API: false
  ENABLE_CREDIT_ELIGIBILITY: false
  ENABLE_CROSS_DOMAIN_CSRF_COOKIE: true
  ENABLE_DISCUSSION_HOME_PANEL: false
  ENABLE_DISCUSSION_SERVICE: false
  ENABLE_EDXNOTES: true
  ENABLE_ENROLLMENT_RESET: true
  ENABLE_EXPORT_GIT: false
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_INSTRUCTOR_ANALYTICS: true
  ENABLE_LTI_PROVIDER: false
  ENABLE_MKTG_SITE: false
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PUBLISHER: false
  ENABLE_READING_FROM_MULTIPLE_HISTORY_TABLES: false
  ENABLE_SPECIAL_EXAMS: false
  ENABLE_SYSADMIN_DASHBOARD: true
  ENABLE_THIRD_PARTY_AUTH: true
  ENABLE_VIDEO_UPLOAD_PIPELINE: false
  SHOW_FOOTER_LANGUAGE_SELECTOR: false
  SHOW_HEADER_LANGUAGE_SELECTOR: false
ID_VERIFICATION_SUPPORT_LINK: https://{{ cookiecutter.global_root_domain }}/support/
LANGUAGE_CODE: en
LANGUAGE_COOKIE: openedx-language-preference
LOGO_URL_PNG: "https://cdn.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}"
PLATFORM_DESCRIPTION: "{{ cookiecutter.global_platform_description }}"
PLATFORM_FACEBOOK_ACCOUNT: http://www.facebook.com/
PLATFORM_NAME: "{{ cookiecutter.global_platform_name }}"
PLATFORM_TWITTER_ACCOUNT: ''
REGISTRATION_EXTRA_FIELDS:
  city: hidden
  confirm_email: hidden
  country: hidden
  gender: hidden
  goals: hidden
  honor_code: hidden
  level_of_education: hidden
  mailing_address: hidden
  terms_of_service: hidden
  year_of_birth: hidden
SESSION_COOKIE_DOMAIN: "{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}"
SESSION_COOKIE_NAME: sessionid
SESSION_COOKIE_SECURE: true
SOCIAL_AUTH_REDIRECT_IS_HTTPS: true
SOCIAL_AUTH_RAISE_EXCEPTIONS: false
SOCIAL_AUTH_BACKEND_ERROR_URL: https://{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}/oauth-error
SOCIAL_MEDIA_FOOTER_URLS:
  linkedin: https://www.linkedin.com/
  twitter: https://twitter.com/
  facebook: https://www.facebook.com/
SUPPORT_SITE_LINK: https://{{ cookiecutter.global_root_domain }}/support/
TIME_ZONE: America/New_York
THIRD_PARTY_AUTH_BACKENDS:
- social_core.backends.google.GoogleOAuth2
- social_core.backends.facebook.FacebookOAuth2
WIKI_ENABLED: false
API_ACCESS_FROM_EMAIL: api-requests@{{ cookiecutter.global_root_domain }}
API_ACCESS_MANAGER_EMAIL: api-access@{{ cookiecutter.global_root_domain }}
BUGS_EMAIL: bugs@{{ cookiecutter.global_root_domain }}
BULK_EMAIL_DEFAULT_FROM_EMAIL: no-reply@{{ cookiecutter.global_root_domain }}
CONTACT_EMAIL: info@{{ cookiecutter.global_root_domain }}
CONTACT_MAILING_ADDRESS: ''
DEFAULT_FEEDBACK_EMAIL: feedback@{{ cookiecutter.global_root_domain }}
DEFAULT_FROM_EMAIL: registration@{{ cookiecutter.global_root_domain }}
FEEDBACK_SUBMISSION_EMAIL: support@{{ cookiecutter.global_root_domain }}
PARTNER_SUPPORT_EMAIL: support@{{ cookiecutter.global_root_domain }}
PASSWORD_RESET_SUPPORT_LINK: support@{{ cookiecutter.global_root_domain }}
PAYMENT_SUPPORT_EMAIL: billing@{{ cookiecutter.global_root_domain }}
PRESS_EMAIL: press@{{ cookiecutter.global_root_domain }}
SERVER_EMAIL: devops@{{ cookiecutter.global_root_domain }}
TECH_SUPPORT_EMAIL: technical@{{ cookiecutter.global_root_domain }}
UNIVERSITY_EMAIL: university@{{ cookiecutter.global_root_domain }}
